services:
  discord-auto-messaging:
    image: ghcr.io/hakiim01/discord-auto-messaging:dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./discord_auto_messaging:/app/discord_auto_messaging
    env_file:
      - .env