apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file compose.yml convert -o k8s
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: discord-auto-messaging
  name: discord-auto-messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discord-auto-messaging
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file compose.yml convert -o k8s
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: discord-auto-messaging
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: ghcr.io/hakiim01/discord-auto-messaging:dev
          name: discord-auto-messaging
          volumeMounts:
            - mountPath: /app/data
              name: discord-auto-messaging-cm0
            - mountPath: /app/discord_auto_messaging
              name: discord-auto-messaging-cm1
      restartPolicy: Always
      volumes:
        - configMap:
            name: discord-auto-messaging-cm0
          name: discord-auto-messaging-cm0
        - configMap:
            name: discord-auto-messaging-cm1
          name: discord-auto-messaging-cm1
